### ISSUE TITLE
Error on Internet Explorer

### ISSUE THREAD

**Issue by jdutriaux** [NodeBB/nodebb-plugin-composer-redactor#73]
Hello, when one of my user try to write a message on Internet Explorer he get this error : 

```
2018-10-11T17:54:16.680Z [18826] - [31merror[39m: /compose
 Error: Failed to lookup view "compose" in views directory "/data/www/nodebb/build/public/templates"
    at Function.render (/data/www/nodebb/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/data/www/nodebb/node_modules/express/lib/response.js:1008:7)
    at content (/data/www/nodebb/src/middleware/render.js:84:15)
    at /data/www/nodebb/node_modules/async/dist/async.js:3880:24
    at replenish (/data/www/nodebb/node_modules/async/dist/async.js:1011:17)
    at /data/www/nodebb/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/data/www/nodebb/node_modules/async/dist/async.js:1041:24)
    at /data/www/nodebb/node_modules/async/dist/async.js:1046:16
    at eachOf (/data/www/nodebb/node_modules/async/dist/async.js:1117:5)
    at _parallel (/data/www/nodebb/node_modules/async/dist/async.js:3879:5)
    at Object.parallelLimit [as parallel] (/data/www/nodebb/node_modules/async/dist/async.js:3962:5)
    at async.waterfall.str (/data/www/nodebb/src/middleware/render.js:79:12)
    at nextTask (/data/www/nodebb/node_modules/async/dist/async.js:5324:14)
    at next (/data/www/nodebb/node_modules/async/dist/async.js:5331:9)
    at /data/www/nodebb/node_modules/async/dist/async.js:969:16
    at /data/www/nodebb/node_modules/async/dist/async.js:473:16
```

He is now using another browser but I juste wanted you to know this issue =).

Thanks,
Halfman.

**Comment by psychobunny** [comment]
This isn't an IE (or browser, really) related problem, the error suggests that NodeBB was not built properly (`./nodebb build` was not run after a plugin install, etc)

Sorry for the late reply!
